export type IconNameType =
  | 'phone'
  | 'mail'
  | 'marker-pin'
  | 'arrow-left'
  | 'arrow-right'
  | 'arrow-up-right'
  | 'chevron-down'
  | 'check'
  | 'check-circle'
  | 'check-2'
  | 'menu'
  | 'star'
  | 'dot'
  | 'close'
  | 'facebook'
  | 'twitter'
  | 'share'
  | 'linkedin'

export type SocialIconNameType =
  'facebook'
  | 'twitter'
  | 'share'
  | 'linkedin'
